CREATE TABLE service_connections (
    user_id BIGINT NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
    service VARCHAR(40) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    encrypted_token TEXT,
    PRIMARY KEY (user_id, service)
);
CREATE TABLE widgets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
    service VARCHAR(40) NOT NULL,
    type VARCHAR(60) NOT NULL,
    title VARCHAR(80) NOT NULL,
    config TEXT NOT NULL,
    refresh_seconds INTEGER NOT NULL CHECK (refresh_seconds BETWEEN 60 AND 86400),
    position INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX idx_widgets_owner ON widgets(user_id, position, id);
